### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by tpoconnor1** [JaouherK/streamDeck-weatherPlugin#10]
have weather as a setup on my stream deck but the weather keeps bugging out.  doesnt display weather or temp just a yellow caution sign.

**Comment by JaouherK** [comment]
Hi @tpoconnor1 , a fix have been created. Waiting for elgato team to roll it out. A fast recovery method is to change fast the provider to openWeather and then back to weather API. 
Also, sometimes Uninstall and reinstall solves the problem.

**Comment by JaouherK** [comment]
@tpoconnor1 did the bug still occur after the latest update?

**Comment by tpoconnor1** [comment]
All good now

**Comment by JaouherK** [comment]
Great thank you.
