### ISSUE TITLE
Updating 

### ISSUE THREAD

**Issue by adamesq** [JaouherK/streamDeck-weatherPlugin#11]
The weather is showing that it's been 69.1F the entire day. I had it sent to push button for refresh, but nothing happens.

**Comment by JaouherK** [comment]
@adamesq does the issue still persist after the last update of the stream deck?

**Comment by adamesq** [comment]
All’s now working well! Thank you!

**Comment by JaouherK** [comment]
@adamesq Thank you for your reply. I am now going to close this issue 😄 
Please consider adding a good note to it ⭐
