### ISSUE TITLE
Round to the closest degree

### ISSUE THREAD

**Issue by thepaulstella** [JaouherK/streamDeck-weatherPlugin#12]
I would like the option to round the closest degree.

Current: 58.37 *F
Desired: 58 *F

**Comment by thepaulstella** [comment]
PR: https://github.com/JaouherK/streamDeck-weatherPlugin/pull/13

**Comment by JaouherK** [comment]
Hi @thepaulstella,  Thank you for the PR. 🙇 
 I will test it today and publish a newer Version
