### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by elimere** [JaouherK/streamDeck-weatherPlugin#15]
Does not pull weather. It randomly stopped working over the weekend. API Key is valid.

**Comment by ShadowMax** [comment]
> Does not pull weather. It randomly stopped working over the weekend. API Key is valid.

try this: https://github.com/JaouherK/streamDeck-weatherPlugin/issues/14#issuecomment-871819926
it's helped me

**Comment by JaouherK** [comment]
Issue solved and will be released in next release
