### ISSUE TITLE
MacOS Fetching data impossible

### ISSUE THREAD

**Issue by mrksnrm** [JaouherK/streamDeck-weatherPlugin#22]
Not working on Mac anymore. Regenerated new API-key, still nothing. 
Also stopped working with windows until regenereated API-key.

**Comment by jumpmancol** [comment]
Same happened to me as well...do you just get a yellow triangle?

**Comment by mrksnrm** [comment]
Yes, yellow triangle appears when pressing weather button on Stream Deck

**Comment by JaouherK** [comment]
@mrksnrm Thanks for reporting this bug.
Did the system recover? 
@jumpmancol do you also face this issue with MacOS?

**Comment by JaouherK** [comment]
The issue already resolved and will be released in next version
