### ISSUE TITLE
Button unresponsive

### ISSUE THREAD

**Issue by MalakieUSN** [JaouherK/streamDeck-weatherPlugin#25]
Added button to stream deck, filled out openweather API key and other info..  Nothing happens. Nothing appears on streamdeck and nothing happens on button press.

**Comment by JaouherK** [comment]
Dear @MalakieUSN , Do you still face this issue?

**Comment by MalakieUSN** [comment]
Have not tried it in a while but the last time I did, it was still not working
________________________________

**Comment by JaouherK** [comment]
The issue already resolved and will be released in next version
