### ISSUE TITLE
update consumed openweather api Version

### ISSUE THREAD

**Issue by atabuchiy** [JaouherK/streamDeck-weatherPlugin#29]
openweather updated their api and now it doesn't work,,,

**Comment by JaouherK** [comment]
Dear @atabuchiy ,
I tested the application for the last couple of days and doesn't seem like there is an issue so far 🤔 
Also, OpenWeather API uses the API version in the request. So we are still safe as long as there is no breaking change.
I will however create another issue to update to the latest version of open API as an enhancement not as a bug.
I will link it later here.
