### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by TinuzzWasTaken** [JaouherK/streamDeck-weatherPlugin#34]
Temp returns NaN when temperature is 0.0C. Changing this to F returns 32F as normal.
![Screenshot 2021-12-03 011620](https://user-images.githubusercontent.com/74241776/144523176-e9c20453-0dec-46a5-a0f2-598f80c82a73.jpg)

**Comment by JaouherK** [comment]
Thank you for reporting this bug. 👍 
This will be released in the next version :)
Please consider adding a start to the project if you like it :)
