### ISSUE TITLE
Displaying NaN

### ISSUE THREAD

**Issue by bcwilly** [JaouherK/streamDeck-weatherPlugin#43]
Please write here a description of the bug and the steps to reproduce it.
Good morning the Plugin is displaying NaN
I logged in and obtained a new API key and the problem persisted 
I am using postal code L5M 0P1 if that helps for some diagnostics

**Comment by JaouherK** [comment]
Dear @bcwilly the fix for that was created by @timholzhey and was already merged.
We are going to add some other fixes and publish the new version
As info, NaN appears when the weather is 0°C or something like that

**Comment by bcwilly** [comment]
Yes given it is Canada and has been -27deg C.. that would be it

 

Brent C. Wilson

Email:  ***@***.***> ***@***.***

Cell: (289) 380-7233
