### ISSUE TITLE
No Temperature

### ISSUE THREAD

**Issue by OneGaming36** [JaouherK/streamDeck-weatherPlugin#45]
Hi,

I've been using the Weather Plugin for a while now without any issues.
Since today I don't get any tempertures for my city anymore. It just shows "NaN".
When I change the City Name from my hometown to e.g. London or New York everything works fine again.
However when I check my city name (with same API Key) on weatherapi it puts out results as usual. Also the temperature is shown there.
If you want to check the issue related to my hometown: I live in "Merseburg" (Germany). A city next to my hometown is "Halle". I have the exact same issue there.

**Comment by OneGaming36** [comment]
Today I'm getting temperatures again, as usual.
At the time it showed "NaN" the temperature was 0.0°C. This might be a bug that needs to be fixed.

**Comment by JaouherK** [comment]
Hi @OneGaming36 and thank you for the report. 
the NaN is indeed a known issue for us. In fact, it was already fixed in the linked merge above. It will be in the next release in addition to other solved issues.
I will close this issue and inform you when the release is happening in the system.
