### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by GDSteelers** [JaouherK/streamDeck-weatherPlugin#5]
Please write here a description of the bug and the steps to reproduce it.
Weather won't work.

**Comment by jahands** [comment]
Mine hasn't been working since yesterday. Here's what it does when I press the button:
![image](https://user-images.githubusercontent.com/10719325/119191190-eacfe380-ba43-11eb-98a7-6028921d7ea9.png)

The API key does work, here's the response from using it in browser:
![image](https://user-images.githubusercontent.com/10719325/119191268-020ed100-ba44-11eb-9824-1ac9d044dec9.png)

**Comment by jahands** [comment]
Fixed it! Just change the Provider to "Open Weather" and then back to "Weather API" and it works again! Guessing just some kind of invalid state because of the update that added Open Weather as a provider.

**Comment by JaouherK** [comment]
@jahands which provider did you select in the drop-down? 
you should be able to select Weather API not Open weather
can you validate this for me?

**Comment by jahands** [comment]
> @jahands which provider did you select in the drop-down?
> you should be able to select Weather API not Open weather
> can you validate this for me?

It was set to Weather API previously when I set it up a few weeks ago, and still was when I double checked it today. Had to switch to Open Weather and then back to Weather API for it to work.

**Comment by JaouherK** [comment]
AH great :) thank you :) Hope you enjoy the plugin
don't forget to click on the "star the project" if you liked it 😄 
Will close the issue now then :)

**Comment by jahands** [comment]
@JaouherK Love the plugin!! Thanks so much for maintaining it, Jaouher :) Have a great day!

**Comment by GDSteelers** [comment]
I tried this workaround but it still does not work for me. This should be an open issue still

**Comment by jahands** [comment]
Should be fixed once v2.1.1 gets released (#6)

**Comment by JaouherK** [comment]
@GDSteelers can you give more details, please?
Are you sure you are having the proper API key for the proper provider? Now, we have two providers.
It might be something else 😞 I can only fix when I have more data 
I will reopen for couple of days until we get further details

**Comment by GDSteelers** [comment]
It has worked fine until the last few days or so. 

I have the same API key I used when it worked properly. I tried both provider drop down options. neither worked. 

What other info can I get you?

**Comment by JaouherK** [comment]
@GDSteelers can you please access this URL and at the end of it add your key? right after key=
http://api.weatherapi.com/v1/current.json?q=London&aqi=no&key=
if it shows something there please copy it here :)

**Comment by GDSteelers** [comment]
{"location":{"name":"London","region":"City of London, Greater London","country":"United Kingdom","lat":51.52,"lon":-0.11,"tz_id":"Europe/London","localtime_epoch":1621710301,"localtime":"2021-05-22 20:05"},"current":{"last_updated_epoch":1621706400,"last_updated":"2021-05-22 19:00","temp_c":13.0,"temp_f":55.4,"is_day":1,"condition":{"text":"Partly cloudy","icon":"//cdn.weatherapi.com/weather/64x64/day/116.png","code":1003},"wind_mph":8.1,"wind_kph":13.0,"wind_degree":250,"wind_dir":"WSW","pressure_mb":1006.0,"pressure_in":30.2,"precip_mm":1.8,"precip_in":0.07,"humidity":58,"cloud":50,"feelslike_c":12.3,"feelslike_f":54.2,"vis_km":10.0,"vis_miles":6.0,"uv":3.0,"gust_mph":8.3,"gust_kph":13.3}}

**Comment by JaouherK** [comment]
So the API works. What happens when you click on the button. does it show what @jahands experienced? the yellow exclamation mark?
can you please change the provider, select the Openweather, push the button, revert to Weather API, and finally push the button one last time. usually, this should fix it.

**Comment by GDSteelers** [comment]
Yes. The yellow exclamation mark. 

I did that. No luck.

**Comment by JaouherK** [comment]
would you mind a zoom call with a share screen session just to see where could possibly be the issue?

**Comment by GDSteelers** [comment]
Sure! Thanks! Want to send me a private message?

**Comment by JaouherK** [comment]
can you post me here your twitter id? I can send you from there directly the invitation

**Comment by GDSteelers** [comment]
@SoundStudio412

**Comment by JaouherK** [comment]
I cannot message you :) can you direct message me @ShinigamiGood

**Comment by GDSteelers** [comment]
Done.

**Comment by GDSteelers** [comment]
Thank you so much for your help! 

If anyone finds this in the future - an uninstall and re-install of the Weather Action fixed the issue for me.

**Comment by JaouherK** [comment]
I will write this troubleshooting session in a separate file for people to check later.
Thank you for your collaboration and contribution to make this plugin better. 👍 
Closing the issue now ☮️

**Comment by lucienimmink** [comment]
FYI: exact same issue happened here. Fix was to switch weather API provider from "Weather API" to "Open Weather" and back again to "Weather API".
