### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by gwhizkids** [JaouherK/streamDeck-weatherPlugin#51]
I've input the API key into the StreamDeck config menu.  However, when I activate the StreamDeck button, I get a yellow triangle (warning) with an exclamation point.  This worked when I first installed it in the middle of 2021, but stopped after a month or so.

**Comment by JaouherK** [comment]
@gwhizkids does this issue still happen for you? sometimes you need when you set the API key to hit "Enter" button after for this to take effect

**Comment by JaouherK** [comment]
The issue is resolved and will be released in the next version
