### ISSUE TITLE
Bug report NaN

### ISSUE THREAD

**Issue by rosavanwinkle** [JaouherK/streamDeck-weatherPlugin#53]
seems like the weather is bugged for me , it was showing for a long time then suddenly it says NaN not sure what it is not a number?
![image](https://user-images.githubusercontent.com/5783693/156069118-73f50349-b93e-4899-a4ac-f37286b9fcfe.png)

**Comment by OneGaming36** [comment]
Seems like this has already been fixed a few weeks ago.
For some reason the fix isn't included in the recent sdPlugin.
Replace the main.js within the plugin with the fixed one from https://github.com/JaouherK/streamDeck-weatherPlugin/tree/master/Sources/com.jk.weather.sdPlugin/plugin and it should work fine. At least it does for me.

**Comment by JaouherK** [comment]
Issue fixed and will soon be released in the store
