### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by powerfulapps** [JaouherK/streamDeck-weatherPlugin#54]
Hi There. Downloaded the Stream Deck Plugin and installed it but under both weather providers i get a Yellow triangle with an exclamation mark when ever l push the button. I have tried reinstalling the plugin and ttried both providers, registered and even tried different cities. Any suggestions. I have even regenerated the API key.
Thanks
Sue Waghorn

**Comment by jcfromkc** [comment]
Same thing..

**Comment by JaouherK** [comment]
Issue resolved and will be released soon to stream deck store
