### ISSUE TITLE
Unable to Retrieve Data from Open Weather API

### ISSUE THREAD

**Issue by magicbycalvin** [JaouherK/streamDeck-weatherPlugin#56]
I have performed the following steps:

- Created and verified my account at openweathermap.org
- Copied my API key into the proper field
- Selected Open Weather for my provider
- Wrote down my city name 
- Chose the temperature unit (I have issues in both F and C)
- Set the fetch frequency to be on push
- Selected hide for display city name (I have issues with whichever display type I choose)
- Select yes to round to closest degree (I have issues with either option)

I still get the yellow triangle with an exclamation point inside of it anytime I push the button. I double checked to verify that I can obtain weather information through the API using the following call (with some information redacted):
https://api.openweathermap.org/data/2.5/weather?q=<REDACTED\>&units=imperial&appid=\<REDACTED\>

While I have never worked with JS, if you could point me to the section of code where the API calls are made and any other relevant code, I would be happy to take a look at the source and see if I can contribute anything useful.

Thank you for your time.

**Comment by JaouherK** [comment]
@magicbycalvin I would love to have a call so we can discuss this. I am unable to reproduce it in the first place unfortunately 😞 
Are you open to this possibility?

**Comment by magicbycalvin** [comment]
@JaouherK I would be more than happy to meet and discuss the issues.

**Comment by magicbycalvin** [comment]
@JaouherK Of course the moment I go to test it again it seems to be functioning properly. Not sure what I did to fix it. I am pretty sure I have rebooted my computer since the last time I tried it though. I was suspecting my VPN may have been part of the problem but it seems to work just fine with it turned on.

I would say you are fine to close the report but I will be sure to let you know if I run into issues again. Thank you for your time!

**Comment by JaouherK** [comment]
Thank you @magicbycalvin :)
have a nice day

**Comment by ashconnor** [comment]
> API key:
> - Your API key is xxxx
> - **Within the next couple of hours, it will be activated and ready to use**
> - You can later create more API keys on your [account page](https://home.openweathermap.org/api_keys)
> - Please, always use your API key in each API call

Emphasis mine for anyone else scratching their head.
